
version: "3.7"

services:
  backend:
    container_name: oca-app-backend
    restart: always
    build: .
    environment:
      - APP_ENV=development
      - APP_PORT=3000
    volumes:
      - ./src:/var/www/oca-app/src
      - ./test:/var/www/oca-app/test
    working_dir: /var/www/oca-app
    ports:
      - "3001:3000"
    links:
      - mysql
    depends_on:
      - mysql
  mysql: # Example Service
    container_name: myapp_mysql
    restart: always
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=Password123#
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Password123#
      - MYSQL_DATABASE=oca-app
    ports:
    - "3308:3306"
    volumes:
    - myapp_mysql_data:/var/lib/mysql
  

volumes:
  myapp_mysql_data:

networks:
  default:
    external:
      name: oca-app

      # ostgres://qtmipeehxyutgf:4097274a27b3ade6f1d1daf1e20cf55043a6b890c5f32991eea7899b7f1fc4dc@ec2-63-32-248-14.eu-west-1.compute.amazonaws.com:5432/d6djl2fa45sf8k